# -*- coding: utf-8 -*-
"""github_to_sheets.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHkEplH8ldU4NWOqnWbqk_ti59t2UPcZ
"""

import requests
import json
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime
from pprint import pprint
import logging
import time
import random
import os

# Configuração de logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Configurações
PROJECT_ID = "PVT_kwHOCqE-wc4ArbN8"
SPREADSHEET_ID = "1vdwjCK2vrPm0L4-sUWcmwFYwz3DaYRzA2PYN-t9kWsQ"
SHEET_NAME = "Sheet1"
GITHUB_TOKEN = os.environ.get("MY_GITHUB_TOKEN")
CREDENTIALS_FILE = "credentials.json"

# Definindo os cabeçalhos esperados
EXPECTED_HEADERS = ["Número", "Título", "Estado", "URL", "Status", "Prioridade", "Complexidade", "Departamento", "Data Atualização"]

# Configuração do GitHub
HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}

# Constantes para controle de taxa
MAX_RETRIES = 5
BATCH_SIZE = 10  # Processar issues em lotes
RATE_LIMIT_DELAY = 60  # Tempo de espera base após atingir limite (segundos)

# Função para testar autenticação GitHub
def test_github_auth():
    try:
        response = requests.get("https://api.github.com/user", headers=HEADERS)
        if response.status_code == 200:
            logging.info("✅ Autenticação no GitHub bem-sucedida")
            return True
        else:
            logging.error(f"❌ Falha na autenticação do GitHub: {response.status_code} - {response.text}")
            return False
    except Exception as e:
        logging.error(f"❌ Erro ao testar autenticação do GitHub: {e}")
        return False

# Função para conectar ao Google Sheets
def get_google_sheet():
    try:
        scope = ["https://spreadsheets.google.com/feeds",
                "https://www.googleapis.com/auth/drive"]
        creds = ServiceAccountCredentials.from_json_keyfile_name(CREDENTIALS_FILE, scope)
        client = gspread.authorize(creds)
        sheet = client.open_by_key(SPREADSHEET_ID).worksheet(SHEET_NAME)

        # Teste de permissão tentando ler os cabeçalhos
        headers = sheet.row_values(1)
        logging.info(f"✅ Conexão com Google Sheets bem-sucedida. Cabeçalhos: {headers}")
        return sheet
    except Exception as e:
        logging.error(f"❌ Erro ao conectar ao Google Sheets: {e}")
        return None

# Função para inicializar a planilha com cabeçalhos corretos se necessário
def initialize_sheet_headers(sheet):
    headers = sheet.row_values(1)

    # Verificar se os cabeçalhos estão vazios ou incompletos
    if not headers or all(h == '' for h in headers) or len(headers) < len(EXPECTED_HEADERS):
        logging.info("📝 Inicializando planilha com cabeçalhos")
        sheet.update('A1:I1', [EXPECTED_HEADERS])  # Adicionar cabeçalhos
        return True

    # Verificar se os cabeçalhos não são únicos
    if len(set(headers)) != len(headers):
        logging.info("📝 Atualizando cabeçalhos para valores únicos")
        sheet.update('A1:I1', [EXPECTED_HEADERS])  # Substituir cabeçalhos
        return True

    return False

# Função para obter todas as issues do projeto GitHub
def get_github_project_data():
    query = """
    query($projectId: ID!) {
      node(id: $projectId) {
        ... on ProjectV2 {
          items(first: 100) {
            nodes {
              content {
                ... on Issue {
                  number
                  title
                  state
                  url
                }
              }
              fieldValues(first: 10) {
                nodes {
                  ... on ProjectV2ItemFieldTextValue {
                    text
                    field { ... on ProjectV2FieldCommon { name } }
                  }
                  ... on ProjectV2ItemFieldNumberValue {
                    number
                    field { ... on ProjectV2FieldCommon { name } }
                  }
                  ... on ProjectV2ItemFieldSingleSelectValue {
                    name
                    field { ... on ProjectV2FieldCommon { name } }
                  }
                }
              }
            }
          }
        }
      }
    }
    """

    try:
        response = requests.post(
            "https://api.github.com/graphql",
            headers=HEADERS,
            json={"query": query, "variables": {"projectId": PROJECT_ID}}
        )

        if response.status_code != 200:
            logging.error(f"❌ Erro na API do GitHub: {response.status_code} - {response.text}")
            return None

        data = response.json()
        if "errors" in data:
            logging.error(f"❌ Erro na consulta GraphQL: {data['errors']}")
            return None

        logging.info("✅ Dados do projeto obtidos do GitHub com sucesso")
        return data
    except Exception as e:
        logging.error(f"❌ Erro ao buscar dados do GitHub: {e}")
        return None

# Função para obter todas as issues do projeto
def extract_all_issues(github_data):
    if not github_data or not github_data.get("data") or not github_data["data"].get("node"):
        logging.error("❌ Dados do GitHub inválidos ou incompletos")
        return []

    nodes = github_data["data"]["node"]["items"]["nodes"]
    issues = []

    for node in nodes:
        if node.get("content") and "number" in node["content"]:
            issues.append(node)

    logging.info(f"✅ Total de {len(issues)} issues encontradas")
    return issues

# Função para obter os números de todas as issues existentes na planilha
def get_existing_issue_numbers(sheet):
    try:
        # Obter todos os valores
        all_values = sheet.get_all_values()
        if len(all_values) <= 1:  # Só tem cabeçalho ou está vazia
            return set()

        # Obter índice da coluna de número da issue
        headers = all_values[0]
        try:
            number_col_index = headers.index("Número")
        except ValueError:
            number_col_index = 0  # Assumir que está na primeira coluna

        # Extrair números das issues
        issue_numbers = set()
        for row in all_values[1:]:  # Pular cabeçalho
            if len(row) > number_col_index and row[number_col_index]:
                try:
                    issue_numbers.add(int(row[number_col_index]))
                except ValueError:
                    # Se não for um número, adiciona como string
                    issue_numbers.add(row[number_col_index])

        logging.info(f"🔍 {len(issue_numbers)} issues já existentes na planilha: {issue_numbers}")
        return issue_numbers
    except Exception as e:
        logging.error(f"❌ Erro ao obter issues existentes: {e}")
        return set()

# Extrair valores dos campos personalizados da issue
def extract_field_values(issue_node):
    field_values = {}

    if "fieldValues" in issue_node and "nodes" in issue_node["fieldValues"]:
        for field in issue_node["fieldValues"]["nodes"]:
            if field and "field" in field and field["field"]:
                field_name = field["field"]["name"]
                if "text" in field:
                    field_values[field_name] = field["text"]
                elif "number" in field:
                    field_values[field_name] = field["number"]
                elif "name" in field:
                    field_values[field_name] = field["name"]

    return field_values

# Função para adicionar uma linha com retry exponencial
def add_row_with_retry(sheet, row_data, append=True):
    retry_count = 0
    backoff_time = 1  # Começamos com 1 segundo de espera

    while retry_count < MAX_RETRIES:
        try:
            if append:
                sheet.append_row(row_data)
            else:
                # Encontrar última linha e escrever na próxima
                last_row = len(sheet.get_all_values()) + 1
                # Converter números da coluna para letras
                cell_range = f"A{last_row}"
                sheet.update(cell_range, [row_data])

            return True
        except gspread.exceptions.APIError as e:
            if "429" in str(e):  # Erro de limite de taxa
                wait_time = backoff_time + random.uniform(0, 1)  # Adicionar jitter
                logging.warning(f"⚠️ Limite de taxa atingido. Tentativa {retry_count+1}/{MAX_RETRIES}. Aguardando {wait_time:.2f}s...")
                time.sleep(wait_time)
                backoff_time = min(backoff_time * 2, RATE_LIMIT_DELAY)  # Duplicar o tempo de espera até o máximo
                retry_count += 1
            else:
                logging.error(f"❌ Erro ao adicionar linha: {e}")
                return False
        except Exception as e:
            logging.error(f"❌ Erro inesperado ao adicionar linha: {e}")
            return False

    logging.error(f"❌ Falha após {MAX_RETRIES} tentativas de adicionar linha")
    return False

# Função para processar lotes de issues
def process_issues_in_batches(sheet, issues, existing_issue_numbers, headers_initialized):
    new_issues_count = 0
    batches = [issues[i:i+BATCH_SIZE] for i in range(0, len(issues), BATCH_SIZE)]

    for batch_index, batch in enumerate(batches):
        logging.info(f"🔄 Processando lote {batch_index+1}/{len(batches)} ({len(batch)} issues)")

        # Criar lote de linhas para adicionar
        batch_rows = []
        for issue_node in batch:
            try:
                issue_number = issue_node["content"]["number"]

                # Verificar se a issue já existe na planilha
                if issue_number in existing_issue_numbers:
                    logging.info(f"ℹ️ Issue #{issue_number} já existe na planilha, pulando...")
                    continue

                # Extrair dados básicos da issue
                issue_data = {
                    "Número": issue_number,
                    "Título": issue_node["content"]["title"],
                    "Estado": issue_node["content"]["state"],
                    "URL": issue_node["content"]["url"],
                    "Data Atualização": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                }

                # Adicionar campos personalizados
                field_values = extract_field_values(issue_node)

                # Mapear campos personalizados para os cabeçalhos esperados
                if "Status" in field_values:
                    issue_data["Status"] = field_values["Status"]
                if "Prioridade" in field_values:
                    issue_data["Prioridade"] = field_values["Prioridade"]
                if "Complexidade" in field_values:
                    issue_data["Complexidade"] = field_values["Complexidade"]
                if "Departamento" in field_values:
                    issue_data["Departamento"] = field_values["Departamento"]

                logging.info(f"📋 Preparando para adicionar issue #{issue_number}: {issue_data['Título']}")

                # Preparar linha para escrita baseada nos cabeçalhos esperados
                row_to_write = []
                for header in EXPECTED_HEADERS:
                    if header in issue_data:
                        row_to_write.append(issue_data[header])
                    else:
                        row_to_write.append("")

                batch_rows.append(row_to_write)

                # Adicionar esta issue à lista de existentes para evitar duplicações
                existing_issue_numbers.add(issue_number)
                new_issues_count += 1

            except Exception as e:
                logging.error(f"❌ Erro ao processar issue: {e}")
                import traceback
                logging.error(f"Traceback: {traceback.format_exc()}")

        # Para cada lote, enviar todas as linhas de uma vez
        if batch_rows:
            if headers_initialized and batch_index == 0 and new_issues_count == len(batch_rows):
                # Achar última linha e atualizar em lote
                last_row = len(sheet.get_all_values()) + 1
                range_label = f"A{last_row}"

                success = False
                retry_count = 0
                backoff_time = 1

                while not success and retry_count < MAX_RETRIES:
                    try:
                        sheet.update(range_label, batch_rows)
                        success = True
                        logging.info(f"✅ Lote {batch_index+1} adicionado com sucesso ({len(batch_rows)} issues)")
                    except gspread.exceptions.APIError as e:
                        if "429" in str(e):
                            wait_time = backoff_time + random.uniform(0, 1)
                            logging.warning(f"⚠️ Limite de taxa atingido no lote. Tentativa {retry_count+1}/{MAX_RETRIES}. Aguardando {wait_time:.2f}s...")
                            time.sleep(wait_time)
                            backoff_time = min(backoff_time * 2, RATE_LIMIT_DELAY)
                            retry_count += 1
                        else:
                            logging.error(f"❌ Erro ao adicionar lote: {e}")
                            # Tentar linha por linha como fallback
                            for row in batch_rows:
                                add_row_with_retry(sheet, row)
                            success = True  # Forçar saída do loop
                    except Exception as e:
                        logging.error(f"❌ Erro inesperado ao adicionar lote: {e}")
                        # Tentar linha por linha como fallback
                        for row in batch_rows:
                            add_row_with_retry(sheet, row)
                        success = True  # Forçar saída do loop
            else:
                # Adicionar linhas individualmente com espera entre elas
                for row in batch_rows:
                    success = add_row_with_retry(sheet, row)
                    if success:
                        logging.info(f"✅ Nova issue adicionada com sucesso")
                    time.sleep(1)  # Pequena pausa entre adições para respeitar limites

        # Pausa entre lotes para evitar problemas de limitação
        if batch_index < len(batches) - 1:  # Se não for o último lote
            wait_time = 5 + random.uniform(0, 2)  # 5-7 segundos entre lotes
            logging.info(f"⏳ Aguardando {wait_time:.2f}s antes do próximo lote...")
            time.sleep(wait_time)

    return new_issues_count

# Função principal
def main():
    # Testar autenticações
    if not test_github_auth():
        return

    # Obter dados do projeto GitHub
    github_data = get_github_project_data()
    if not github_data:
        return

    # Extrair todas as issues
    all_issues = extract_all_issues(github_data)
    if not all_issues:
        logging.info("ℹ️ Nenhuma issue encontrada no projeto GitHub")
        return

    # Conectar ao Google Sheets
    sheet = get_google_sheet()
    if not sheet:
        return

    # Inicializar cabeçalhos se necessário
    headers_initialized = initialize_sheet_headers(sheet)

    # Obter issues já existentes na planilha
    existing_issue_numbers = get_existing_issue_numbers(sheet)

    # Processar issues em lotes para evitar problemas de rate limit
    new_issues_count = process_issues_in_batches(sheet, all_issues, existing_issue_numbers, headers_initialized)

    logging.info(f"✨ Processamento concluído! {new_issues_count} novas issues adicionadas à planilha.")

if __name__ == "__main__":
    main()
