# -*- coding: utf-8 -*-
"""github_to_sheets.ipynb
Automatically generated by Colab.
"""

import requests
import json
import gspread
from oauth2client.service_account import ServiceAccountCredentials
from datetime import datetime
from pprint import pprint
import logging
import time
import random
import os
import sys

# Configuração de logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Configurações
PROJECT_ID = "PVT_kwHOCqE-wc4ArbN8"
SPREADSHEET_ID = "1vdwjCK2vrPm0L4-sUWcmwFYwz3DaYRzA2PYN-t9kWsQ"
SHEET_NAME = "Sheet1"
CREDENTIALS_FILE = "credentials.json"
# Modifique esta parte:
GITHUB_TOKEN = os.environ.get('GH_TOKEN')  # Deve bater com o nome no workflow
if not GITHUB_TOKEN:
    logging.error("❌ Token do GitHub não encontrado nas variáveis de ambiente")
    sys.exit(1)

HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",  # Use a variável já obtida
    "Accept": "application/vnd.github+json"
}

EXPECTED_HEADERS = ["Número", "Título", "Estado", "URL", "Status", "Prioridade", "Complexidade", "Departamento", "Data Atualização"]


MAX_RETRIES = 5
BATCH_SIZE = 10
RATE_LIMIT_DELAY = 60

def test_github_auth():
    try:
        response = requests.get("https://api.github.com/user", headers=HEADERS)
        if response.status_code == 200:
            logging.info("✅ Autenticação no GitHub bem-sucedida")
            return True
        else:
            logging.error(f"❌ Falha na autenticação do GitHub: {response.status_code} - {response.text}")
            return False
    except Exception as e:
        logging.error(f"❌ Erro ao testar autenticação do GitHub: {e}")
        return False

def get_google_sheet():
    try:
        scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
        creds = ServiceAccountCredentials.from_json_keyfile_name(CREDENTIALS_FILE, scope)
        client = gspread.authorize(creds)
        sheet = client.open_by_key(SPREADSHEET_ID).worksheet(SHEET_NAME)
        headers = sheet.row_values(1)
        logging.info(f"✅ Conexão com Google Sheets bem-sucedida. Cabeçalhos: {headers}")
        return sheet
    except Exception as e:
        logging.error(f"❌ Erro ao conectar ao Google Sheets: {e}")
        return None

def initialize_sheet_headers(sheet):
    headers = sheet.row_values(1)
    if not headers or all(h == '' for h in headers) or len(headers) < len(EXPECTED_HEADERS) or len(set(headers)) != len(headers):
        logging.info("📝 Inicializando ou atualizando cabeçalhos")
        sheet.update('A1:I1', [EXPECTED_HEADERS])
        return True
    return False

def get_github_project_data():
    query = """
    query($projectId: ID!) {
      node(id: $projectId) {
        ... on ProjectV2 {
          items(first: 100) {
            nodes {
              content {
                ... on Issue {
                  number
                  title
                  state
                  url
                }
              }
              fieldValues(first: 10) {
                nodes {
                  ... on ProjectV2ItemFieldTextValue {
                    text
                    field { ... on ProjectV2FieldCommon { name } }
                  }
                  ... on ProjectV2ItemFieldNumberValue {
                    number
                    field { ... on ProjectV2FieldCommon { name } }
                  }
                  ... on ProjectV2ItemFieldSingleSelectValue {
                    name
                    field { ... on ProjectV2FieldCommon { name } }
                  }
                }
              }
            }
          }
        }
      }
    }
    """
    try:
        response = requests.post("https://api.github.com/graphql", headers=HEADERS, json={"query": query, "variables": {"projectId": PROJECT_ID}})
        if response.status_code != 200:
            logging.error(f"❌ Erro na API do GitHub: {response.status_code} - {response.text}")
            return None
        data = response.json()
        if "errors" in data:
            logging.error(f"❌ Erro na consulta GraphQL: {data['errors']}")
            return None
        logging.info("✅ Dados do projeto obtidos do GitHub com sucesso")
        return data
    except Exception as e:
        logging.error(f"❌ Erro ao buscar dados do GitHub: {e}")
        return None

def extract_all_issues(github_data):
    if not github_data or not github_data.get("data") or not github_data["data"].get("node"):
        logging.error("❌ Dados do GitHub inválidos ou incompletos")
        return []
    return [node for node in github_data["data"]["node"]["items"]["nodes"] if node.get("content") and "number" in node["content"]]

def get_existing_issue_numbers(sheet):
    try:
        all_values = sheet.get_all_values()
        if len(all_values) <= 1:
            return set()
        headers = all_values[0]
        number_col_index = headers.index("Número") if "Número" in headers else 0
        return set(int(row[number_col_index]) for row in all_values[1:] if len(row) > number_col_index and row[number_col_index].isdigit())
    except Exception as e:
        logging.error(f"❌ Erro ao obter issues existentes: {e}")
        return set()

def extract_field_values(issue_node):
    field_values = {}
    for field in issue_node.get("fieldValues", {}).get("nodes", []):
        if field and "field" in field and field["field"]:
            name = field["field"]["name"]
            value = field.get("text") or field.get("number") or field.get("name")
            field_values[name] = value
    return field_values

def add_row_with_retry(sheet, row_data):
    retry_count = 0
    backoff_time = 1
    while retry_count < MAX_RETRIES:
        try:
            sheet.append_row([str(cell) for cell in row_data])
            return True
        except gspread.exceptions.APIError as e:
            if "429" in str(e):
                wait_time = backoff_time + random.uniform(0, 1)
                logging.warning(f"⚠️ Rate limit atingido. Tentativa {retry_count+1}. Aguardando {wait_time:.2f}s...")
                time.sleep(wait_time)
                backoff_time = min(backoff_time * 2, RATE_LIMIT_DELAY)
                retry_count += 1
            else:
                logging.error(f"❌ Erro ao adicionar linha: {e}")
                return False
        except Exception as e:
            logging.error(f"❌ Erro inesperado: {e}")
            return False
    return False

def process_issues_in_batches(sheet, issues, existing_issue_numbers, headers_initialized):
    new_issues_count = 0
    batches = [issues[i:i + BATCH_SIZE] for i in range(0, len(issues), BATCH_SIZE)]

    for batch_index, batch in enumerate(batches):
        logging.info(f"🔄 Processando lote {batch_index+1}/{len(batches)}")
        batch_rows = []
        for node in batch:
            try:
                issue = node["content"]
                number = issue["number"]
                if number in existing_issue_numbers:
                    logging.info(f"ℹ️ Issue #{number} já existe. Pulando...")
                    continue
                data = {
                    "Número": number,
                    "Título": issue["title"],
                    "Estado": issue["state"],
                    "URL": issue["url"],
                    "Data Atualização": datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                }
                fields = extract_field_values(node)
                for k in ["Status", "Prioridade", "Complexidade", "Departamento"]:
                    data[k] = fields.get(k, "")
                row = [str(data.get(header, "")) for header in EXPECTED_HEADERS]
                batch_rows.append(row)
                existing_issue_numbers.add(number)
                new_issues_count += 1
            except Exception as e:
                logging.error(f"❌ Erro ao processar issue: {e}")

        for row in batch_rows:
            if add_row_with_retry(sheet, row):
                logging.info("✅ Linha adicionada")
            time.sleep(1)

        if batch_index < len(batches) - 1:
            wait_time = 5 + random.uniform(0, 2)
            logging.info(f"⏳ Esperando {wait_time:.2f}s antes do próximo lote...")
            time.sleep(wait_time)

    return new_issues_count

def main():
    logging.info("Variáveis de ambiente disponíveis:")
    for key in ['GH_TOKEN', 'GITHUB_TOKEN', 'GOOGLE_APPLICATION_CREDENTIALS']:
    logging.info(f"{key}: {'*****' if os.environ.get(key) else 'Não encontrada'}")
    if not test_github_auth():
        return
    github_data = get_github_project_data()
    if not github_data:
        return
    issues = extract_all_issues(github_data)
    if not issues:
        logging.info("ℹ️ Nenhuma issue encontrada.")
        return
    sheet = get_google_sheet()
    if not sheet:
        return
    headers_initialized = initialize_sheet_headers(sheet)
    existing_issues = get_existing_issue_numbers(sheet)
    new_count = process_issues_in_batches(sheet, issues, existing_issues, headers_initialized)
    logging.info(f"✨ {new_count} novas issues adicionadas.")

if __name__ == "__main__":
    main()
