name: GitHub to Google Sheets Automation

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'  # 4 vezes ao dia
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          pip install gspread oauth2client requests

      - name: Criar arquivo de credenciais do Google
        env:
          GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
        run: |
          echo "$GOOGLE_CREDS" | tr -d '\r' > credentials.json

      - name: Executar script Python
        env:
          GOOGLE_APPLICATION_CREDENTIALS: credentials.json
        run: |
          python automations/github_to_sheets.py
